#
# Copyright (c) 2026, re-thc. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.  Oracle designates this
# particular file as subject to the "Classpath" exception as provided
# by Oracle in the LICENSE file that accompanied this code.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#

name: 'Compiler cache'
description: 'Keep native compiler results between builds of the same profile'
inputs:
  platform:
    required: true
    description: 'Target OS and architecture'
  debug-level:
    required: true
    description: 'Release or fastdebug'
  toolchain:
    required: true
    description: 'Compiler toolchain version'
runs:
  using: composite
  steps:
    - name: 'Set cache location'
      shell: bash
      run: echo "CCACHE_DIR=$RUNNER_TEMP/ccache" >> "$GITHUB_ENV"

    - name: 'Restore cache'
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ${{ runner.temp }}/ccache
        key: ccache-v1-${{ inputs.platform }}-${{ inputs.debug-level }}-${{ inputs.toolchain }}-${{ hashFiles('bin/configure-dev', 'make/autoconf/**') }}-${{ github.sha }}
        restore-keys: |
          ccache-v1-${{ inputs.platform }}-${{ inputs.debug-level }}-${{ inputs.toolchain }}-${{ hashFiles('bin/configure-dev', 'make/autoconf/**') }}-

    - name: 'Configure cache'
      shell: bash
      run: |
        ccache --max-size=750M
        ccache --zero-stats
